import { a, h, f, p, v } from './tipos.js';
import type { ModeloVentaneria } from './tipos.js';

/** Modelos de la familia 744. */
export const modelos744: ModeloVentaneria[] = [
  {
    id: '744-2-hojas',
    nombre: '744 2 hojas',
    sistema: '744',
    diseno: {
      tipo: 'corredera',
      apiladas: false,
      hojas: [
        { tipo: 'corredera', proporcion: 0.5 },
        { tipo: 'corredera', proporcion: 0.5 },
      ],
    },
    ejemplo: { ancho: 100, alto: 136.5 },
    piezas: [
      p('ALN-392', 'CABEZAL', a(), 1),
      p('ALN-387', 'SILLAR', a(), 1),
      p('ALN-393', 'JAMBA', h(1.1), 2),
      p('ALN-391', 'ENGANCHE 744', h(2.5), 2),
      p('ALN-388', 'TRASLAPE 744', h(2.5), 2),
      p('ALN-389', 'HORIZONTAL SUP.', a(0.6, 2), 2),
      p('ALNA-390', 'HORIZONTAL INF.', a(0.6, 2), 2),
    ],
    vidrios: [v('HOJAS', 'vidrio', 5, h(9), { base: 'ancho', resta: 12.2, divisor: 2 }, 2)],
    empaqueTipo: '744',
    empaqueFactor: 1,
    empaqueExtraPorHoja: 0,
    accesorios: [
      { seccion: 'TORNILLERIA', descripcion: '8 X 3/4¨ HOJAS', cantidad: 12 },
      { seccion: 'TORNILLERIA', descripcion: '8 X 1 1/2¨', cantidad: 10 },
      { seccion: 'TORNILLERIA', descripcion: '8 X 1/2¨', cantidad: 6 },
      { seccion: 'CHAZOS', descripcion: '1/4¨', cantidad: 10 },
      { seccion: 'RODACHINAS', descripcion: '744 ACERO', cantidad: 2 },
      { seccion: 'GUIAS', descripcion: '744 INFERIORES', cantidad: 2 },
      { seccion: 'GUIAS', descripcion: '744 SUPERIORES', cantidad: 3 },
      { seccion: 'SEGURO', descripcion: 'JAGUAR DOBLE', cantidad: 1 },
    ],
  },

  {
    id: '744-4-hojas',
    nombre: '744 4 hojas',
    sistema: '744',
    diseno: {
      tipo: 'corredera',
      apiladas: false,
      hojas: [
        { tipo: 'corredera', proporcion: 0.25 },
        { tipo: 'corredera', proporcion: 0.25 },
        { tipo: 'corredera', proporcion: 0.25 },
        { tipo: 'corredera', proporcion: 0.25 },
      ],
    },
    ejemplo: { ancho: 266.7, alto: 150 },
    piezas: [
      p('ALN-392', 'CABEZAL', a(), 1),
      p('ALN-387', 'SILLAR', a(), 1),
      p('ALN-393', 'JAMBA', h(1.1), 2),
      p('ALN-391', 'ENGANCHE 744', h(2.5), 4),
      p('ALN-388', 'TRASLAPE 744', h(2.5), 4),
      p('ALN-403', 'ADAPTADOR 744', h(2.5), 1),
      p('ALN-389', 'HORIZONTAL SUP.', a(-1, 4), 4),
      p('ALNA-390', 'HORIZONTAL INF.', a(-1, 4), 4),
    ],
    vidrios: [v('HOJAS', 'vidrio', 5, h(9), a(20.6, 4), 4)],
    empaqueTipo: '744',
    empaqueFactor: 1,
    empaqueExtraPorHoja: 0,
    accesorios: [
      { seccion: 'TORNILLERIA', descripcion: '8 X 3/4¨', cantidad: 36 },
      { seccion: 'TORNILLERIA', descripcion: '8 X 1 1/2¨', cantidad: 10 },
      { seccion: 'TORNILLERIA', descripcion: '8 X 1/2¨', cantidad: 12 },
      { seccion: 'CHAZOS', descripcion: '1/4¨', cantidad: 10 },
      { seccion: 'RODACHINAS', descripcion: '744 ACERO', cantidad: 4 },
      { seccion: 'GUIAS', descripcion: '744 INF.', cantidad: 4 },
      { seccion: 'GUIAS', descripcion: '744 SUP.', cantidad: 4 },
      { seccion: 'SEGURO', descripcion: 'JAGUAR DOBLE', cantidad: 1 },
      { seccion: 'SEGURO', descripcion: 'UÑERO DOBLE', cantidad: 1 },
    ],
  },

  {
    id: '744-3-hojas-parche',
    nombre: '744 3 hojas 1 parche',
    sistema: '744',
    diseno: {
      tipo: 'corredera',
      apiladas: false,
      hojas: [
        { tipo: 'corredera', proporcion: 0.333 },
        { tipo: 'corredera', proporcion: 0.333 },
        { tipo: 'fija', proporcion: 0.334 },
      ],
    },
    ejemplo: { ancho: 300, alto: 200 },
    piezas: [
      p('ALN-392', 'CABEZAL', a(), 1),
      p('ALN-387', 'SILLAR', a(), 1),
      p('ALN-393', 'JAMBA', h(1.5), 2),
      p('ALN-391', 'ENGANCHE 744 (FIJA)', h(0.3), 1),
      p('ALN-388', 'TRASLAPE 744 (FIJA)', h(0.3), 1),
      p('ALN-389', 'HORIZONTAL SUP. (FIJA)', a(-3, 3), 1),
      p('ALNA-390', 'HORIZONTAL INF. (FIJA)', a(-3, 3), 1),
      p('ALN-391', 'ENGANCHE 744 (CORR.)', h(2.5), 3),
      p('ALN-388', 'TRASLAPE 744 (CORR.)', h(2.5), 1),
      p('ALN-389', 'HORIZONTAL SUP. (CORR.)', a(-3, 3), 2),
      p('ALNA-390', 'HORIZONTAL INF. (CORR.)', a(-3, 3), 2),
      p('ALN403', 'ADAPTADOR 744', h(0.3), 1),
      p('', 'ANGULO 3/4 x 3/4', a(-3, 3), 1),
    ],
    vidrios: [
      v('HOJA FIJA', 'vidrio', 5, h(7.3), { base: 'ancho', resta: 13.5, divisor: 3 }, 1),
      v('ENGA. Y ENGAN.', 'vidrio', 5, h(9.5), a(10.8, 3), 1),
      v('ENGA. Y TRASL.', 'vidrio', 5, h(9.5), { base: 'ancho', resta: 13.5, divisor: 3 }, 1),
    ],
    empaqueTipo: '744',
    empaqueFactor: 1,
    empaqueExtraPorHoja: 0,
    accesorios: [
      { seccion: 'TORNILLERIA', descripcion: '8 X 3/4¨', cantidad: 16 },
      { seccion: 'TORNILLERIA', descripcion: '8 X 1 1/2¨', cantidad: 10 },
      { seccion: 'TORNILLERIA', descripcion: '8 X 1/2¨', cantidad: 6 },
      { seccion: 'CHAZOS', descripcion: '1/4¨', cantidad: 10 },
      { seccion: 'RODACHINAS', descripcion: '744 ACERO', cantidad: 4 },
      { seccion: 'GUIAS', descripcion: '744 INFERIORES', cantidad: 4 },
      { seccion: 'GUIAS', descripcion: '744 SUPERIORES', cantidad: 4 },
      { seccion: 'SEGURO', descripcion: 'JAGUAR DOBLE', cantidad: 1 },
    ],
  },
];
