import { a, h, f, p, v } from './tipos.js';
import type { ModeloVentaneria } from './tipos.js';

/** Modelos de la familia Pb. */
export const modelosPb: ModeloVentaneria[] = [
  {
    id: 'pb-tubular-1x1.2',
    nombre: 'P.B. tubular 1x1.2',
    sistema: 'P.B.',
    diseno: {
      tipo: 'batiente',
      apiladas: false,
      hojas: [{ tipo: 'batiente', proporcion: 1 }],
    },
    ejemplo: { ancho: 149.4, alto: 150 },
    piezas: [
      p('PU-057', 'U 2X1 SUPER CORRIDA', h(), 2),
      p('PU-057', 'U 2X1 SUPER CORRIDA', a(5), 1),
      p('ALN-1101', 'TUBO 1 1/2 X 1 1/2 CON ADAPTADOR', h(4), 2),
      p('ALN-1101', 'TUBO 1 1/2 X 1 1/2 CON ADAPTADOR', a(14), 2),
      p('ALN-1175', 'ADAPTADOR', a(14), 1),
      p('ALN-1102', 'TUBO 3 X 1 1/2 CON ADAPTADOR', a(14), 1, 90),
      p('', 'ANGULO CHAPETA 1x1¨', f(3.4), 4, 90),
      p('', 'ANGULO CHAPETA 1x1¨', f(2.8), 4, 90),
      p('', 'ANGULO CHAPETA 1x1¨', f(2.2), 4, 90),
      p('', 'PISAVIDRIO HORIZONTAL', a(14), 4, 90),
      p('', 'PISAVIDRIO PARAL', f(46), 2),
      p('', 'PISAVIDRIO PARAL', f(75), 2),
    ],
    vidrios: [
      v('VIDRIO', 'vidrio', 4, h(29.8, 2), a(14.8), 1),
      v('VIDRIO', 'vidrio', 4, h(17.4, 2), a(14.8), 1),
    ],
    empaqueTipo: 'ESTRELLA',
    empaqueFactor: 2,
    empaqueExtraPorHoja: 24.8,
    accesorios: [
      { seccion: 'REMACHES', descripcion: 'POP. 4 - 4¨', cantidad: 40 },
      { seccion: 'REMACHES', descripcion: 'POP. 5 - 4¨', cantidad: 8 },
      { seccion: 'TORNILLOS', descripcion: 'AVELLANADO 8X 2 1/2', cantidad: 8 },
      { seccion: 'CHAZOS', descripcion: '1/4¨', cantidad: 8 },
      { seccion: 'BISAGRAS', descripcion: 'OMEGA', cantidad: 4 },
      { seccion: 'CHAPA', descripcion: 'LLAVE-BOTON', cantidad: 1 },
    ],
  },

  {
    id: 'pb-2-hojas',
    nombre: 'P.B. 2 hojas 1x1.2',
    sistema: 'P.B.',
    diseno: {
      tipo: 'batiente',
      apiladas: false,
      hojas: [
        { tipo: 'batiente', proporcion: 0.5 },
        { tipo: 'batiente', proporcion: 0.5 },
      ],
    },
    ejemplo: { ancho: 200, alto: 200 },
    piezas: [
      p('PU-057', 'U 2X1 SUPERCORRIDA', h(), 2),
      p('PU-057', 'U 2X1 SUPERCORRIDA', a(5), 1),
      p('ALN-1101', 'TUBO 1 1/2 X 1 1/2 CON ADAPTADOR', h(4), 4),
      p('ALN-1101', 'TUBO 1 1/2 X 1 1/2 CON ADAPTADOR', a(6.5, 2), 4),
      p('ALN-1175', 'ADAPTADOR', a(6.5, 2), 2),
      p('ALN-1102', 'TUBO 3 X 1 1/2 CON ADAPTADOR', a(6.5, 2), 2, 90),
      p('', 'ANGULO CHAPETA 1x1¨', f(3.4), 8, 90),
      p('', 'ANGULO CHAPETA 1x1¨', f(2.8), 8, 90),
      p('', 'ANGULO CHAPETA 1x1¨', f(2.2), 8, 90),
      p('', 'PISAVIDRIO HORIZONTAL', a(6.5, 2), 8, 90),
      p('', 'PISAVIDRIO PARALES', f(95), 4),
      p('', 'PISAVIDRIO PARALES', f(92.9), 4),
    ],
    vidrios: [
      v('VIDRIO', 'acrilico', 4, h(29.8, 2), a(8.1, 2), 2),
      v('VIDRIO', 'acrilico', 4, h(17.4, 2), a(8.1, 2), 2),
    ],
    empaqueTipo: 'ESTRELLA',
    empaqueFactor: 2,
    empaqueExtraPorHoja: 24.8,
    accesorios: [
      { seccion: 'REMACHES', descripcion: 'POP. 4 - 4¨', cantidad: 40 },
      { seccion: 'REMACHES', descripcion: 'POP. 5 - 4¨', cantidad: 16 },
      { seccion: 'TORNILLOS', descripcion: 'AVELLANADO 8X 2 1/2', cantidad: 8 },
      { seccion: 'CHAZOS', descripcion: '1/4¨', cantidad: 8 },
      { seccion: 'BISAGRAS', descripcion: 'OMEGA', cantidad: 8 },
      { seccion: 'CHAPA', descripcion: 'LLAVE-BOTON', cantidad: 1 },
    ],
  },

  {
    id: 'pb-tubular-3x1',
    nombre: 'P.B. tubular 3x1 proyectante',
    sistema: 'P.B.',
    diseno: {
      tipo: 'batiente',
      apiladas: false,
      hojas: [{ tipo: 'batiente', proporcion: 1 }],
    },
    ejemplo: { ancho: 90, alto: 200 },
    piezas: [
      p('PU-057', 'U 2X1 SUPERCORRIDA', h(), 2),
      p('PU-057', 'U 2X1 SUPERCORRIDA', a(5), 1),
      p('ALN-1102', 'TUBO 3 X 1 1/2 CON ADAPTADOR', h(4.1), 2),
      p('ALN-1102', 'TUBO 3 X 1 1/2 CON ADAPTADOR', a(-42.4, 2), 3),
      p('ALN-1175', 'ADAPTADOR', a(-42.4, 2), 1),
      p('', 'ANGULO CHAPETA 1x1¨', f(3.4), 4, 90),
      p('', 'ANGULO CHAPETA 1x1¨', f(2.8), 4, 90),
      p('', 'ANGULO CHAPETA 1x1¨', f(2.2), 4, 90),
      p('', 'PISAVIDRIO HORIZONTAL', a(-42.2, 2), 4, 90),
      p('', 'PISAVIDRIO PARALES', f(92.1), 2, 45),
    ],
    vidrios: [
      v('VIDRIO', 'vidrio', 4, h(39.6, 2), a(-40.8, 2), 1),
      v('VIDRIO', 'vidrio', 4, h(27.2, 2), a(-40.8, 2), 1),
    ],
    empaqueTipo: 'ESTRELLA',
    empaqueFactor: 2,
    empaqueExtraPorHoja: 24.8,
    accesorios: [
      { seccion: 'REMACHES', descripcion: 'POP. 4 - 4¨', cantidad: 40 },
      { seccion: 'REMACHES', descripcion: 'POP. 5 - 4¨', cantidad: 8 },
      { seccion: 'TORNILLOS', descripcion: 'AVELLANADO 8X 2 1/2', cantidad: 8 },
      { seccion: 'CHAZOS', descripcion: '1/4¨', cantidad: 8 },
      { seccion: 'BISAGRAS', descripcion: 'OMEGA', cantidad: 4 },
      { seccion: 'CHAPA', descripcion: 'LLAVE-BOTON', cantidad: 1 },
    ],
  },

  {
    id: 'pb-tubular-3x1-2-hojas',
    nombre: 'P.B. tubular 3x1 2 hojas',
    sistema: 'P.B.',
    diseno: {
      tipo: 'batiente',
      apiladas: false,
      hojas: [
        { tipo: 'batiente', proporcion: 0.5 },
        { tipo: 'batiente', proporcion: 0.5 },
      ],
    },
    ejemplo: { ancho: 200, alto: 200 },
    piezas: [
      p('PU-057', 'U 2X1 SUPERCORRIDA', h(), 2),
      p('PU-057', 'U 2X1 SUPERCORRIDA', a(5), 1),
      p('ALN-1102', 'TUBO 3 X 1 1/2 CON ADAPTADOR', h(4.1), 4),
      p('ALN-1102', 'TUBO 3 X 1 1/2 CON ADAPTADOR', a(42.6, 2), 6),
      p('ALN-1175', 'ADAPTADOR', a(42.6, 2), 2),
      p('', 'ANGULO CHAPETA 1x1¨', f(3.4), 4, 90),
      p('', 'ANGULO CHAPETA 1x1¨', f(2.8), 4, 90),
      p('', 'ANGULO CHAPETA 1x1¨', f(2.2), 4, 90),
      p('', 'PISAVIDRIO HORIZONTAL', a(42.6, 2), 8, 90),
      p('', 'PISAVIDRIO PARALES', f(92.1), 4, 90),
    ],
    vidrios: [
      v('VIDRIO', 'acrilico', 4, h(39.6, 2), a(44.2, 2), 2),
      v('VIDRIO', 'acrilico', 4, h(27.2, 2), a(44.2, 2), 2),
    ],
    empaqueTipo: 'ESTRELLA',
    empaqueFactor: 2,
    empaqueExtraPorHoja: 24.8,
    accesorios: [
      { seccion: 'REMACHES', descripcion: 'POP. 4 - 4¨', cantidad: 40 },
      { seccion: 'REMACHES', descripcion: 'POP. 5 - 4¨', cantidad: 8 },
      { seccion: 'TORNILLOS', descripcion: 'AVELLANADO 8X 2 1/2', cantidad: 8 },
      { seccion: 'CHAZOS', descripcion: '1/4¨', cantidad: 8 },
      { seccion: 'BISAGRAS', descripcion: 'OMEGA', cantidad: 8 },
      { seccion: 'CHAPA', descripcion: 'LLAVE-BOTON', cantidad: 1 },
    ],
  },

  {
    id: 'puerta-botagua-744',
    nombre: 'Puerta B. botagua y 744',
    sistema: 'P.B.',
    diseno: {
      tipo: 'batiente',
      apiladas: false,
      hojas: [{ tipo: 'batiente', proporcion: 1 }],
    },
    ejemplo: { ancho: 70, alto: 180 },
    piezas: [
      p('S.268', 'BOTAGUA CORRIENTE', h(), 2),
      p('S.268', 'BOTAGUA CORRIENTE', a(2.8), 2),
      p('ALN-388', 'TRASLAPE DE 744', h(2.9), 2, 45),
      p('ALN-388', 'TRASLAPE DE 744', a(3.6), 2, 45),
    ],
    vidrios: [v('ACRILICO ENCHAPE BLANCO', 'acrilico', 4, h(10), a(10.7), 1)],
    empaqueTipo: '5020',
    empaqueFactor: 1,
    empaqueExtraPorHoja: 0,
    accesorios: [
      { seccion: 'REMACHES', descripcion: 'POP. 4 - 4¨', cantidad: 14 },
      { seccion: 'TORNILLOS', descripcion: 'AVELLANADO 10 * 2¨', cantidad: 6 },
      { seccion: 'CHAZOS', descripcion: 'PLASTICO 1/4¨', cantidad: 6 },
      { seccion: 'BISAGRAS', descripcion: 'OMEGA', cantidad: 3 },
      { seccion: 'MANIJA', descripcion: 'S-540', cantidad: 1 },
      { seccion: 'SEGURO', descripcion: 'ALEMAN', cantidad: 1 },
    ],
  },
];
