import { a, h, f, p, v } from './tipos.js';
import type { ModeloVentaneria } from './tipos.js';

/** Modelos de la familia 7038. */
export const modelos7038: ModeloVentaneria[] = [
  {
    id: '7038-2-hojas',
    nombre: '7038 2 hojas',
    sistema: '7038',
    diseno: {
      tipo: 'corredera',
      apiladas: false,
      hojas: [
        { tipo: 'corredera', proporcion: 0.5 },
        { tipo: 'corredera', proporcion: 0.5 },
      ],
    },
    ejemplo: { ancho: 210, alto: 230 },
    piezas: [
      p('ALN-700', 'CABEZAL', a(), 1),
      p('ALN-775', 'SILLAR', a(), 1),
      p('ALN-702', 'JAMBA', h(1.5), 2),
      p('ALN-705', 'ENGANCHE 7038', h(3.5), 2),
      p('ALN-704', 'TRASLAPE 7038', h(3.5), 2),
      p('ALN-703', 'HORIZONTAL SUP.', a(-0.7, 2), 4),
    ],
    vidrios: [v('HOJAS', 'vidrio', 6, h(16.7), a(22.3, 2), 2)],
    empaqueTipo: '7038',
    empaqueFactor: 1,
    empaqueExtraPorHoja: 0,
    accesorios: [
      { seccion: 'TORNILLERIA', descripcion: '10 X 1¨', cantidad: 20 },
      { seccion: 'TORNILLERIA', descripcion: '10 X 1¨', cantidad: 6 },
      { seccion: 'TORNILLERIA', descripcion: '10 X 2¨', cantidad: 10 },
      { seccion: 'CHAZOS', descripcion: '1/4¨', cantidad: 10 },
      { seccion: 'RODACHINAS', descripcion: '7038', cantidad: 2 },
      { seccion: 'GUIAS', descripcion: '7038 SUP', cantidad: 4 },
      { seccion: 'GUIAS', descripcion: '7038 INF', cantidad: 4 },
      { seccion: 'MANIJA', descripcion: 'ALUMINIO', cantidad: 1 },
      { seccion: 'SEGURO', descripcion: 'OVERSEA', cantidad: 1 },
    ],
  },

  {
    id: '7038-3-hojas',
    nombre: '7038 3 hojas',
    sistema: '7038',
    diseno: {
      tipo: 'corredera',
      apiladas: false,
      hojas: [
        { tipo: 'corredera', proporcion: 0.333 },
        { tipo: 'corredera', proporcion: 0.333 },
        { tipo: 'fija', proporcion: 0.334 },
      ],
    },
    ejemplo: { ancho: 360, alto: 230 },
    piezas: [
      p('ALN-700', 'CABEZAL', a(), 1),
      p('ALN-775', 'SILLAR', a(), 1),
      p('ALN-702', 'JAMBA', h(1.5), 2),
      p('ALN-705', 'ENGANCHE 7038 (FIJA)', h(0.4), 1),
      p('ALN-704', 'TRASLAPE 7038 (FIJA)', h(0.4), 1),
      p('ALN-703', 'HORIZONTAL SUP. (FIJA)', a(-7.2, 3), 1),
      p('ALN-703', 'HORIZONTAL INF. (FIJA)', a(-7.2, 3), 1),
      p('ALN-705', 'ENGANCHE 7038 (CORR.)', h(3.5), 3),
      p('ALN-704', 'TRASLAPE 7038 (CORR.)', h(3.5), 1),
      p('ALN-703', 'HORIZONTAL SUP. (CORR.)', a(-7.2, 3), 2),
      p('ALN-703', 'HORIZONTAL INF. (CORR.)', a(-7.2, 3), 2),
      p('', 'ANGULO 3/4 x 3/4', a(-7.2, 3), 1),
    ],
    vidrios: [
      v('HOJA FIJA', 'vidrio', 6, h(13.9), a(26.7, 3), 1),
      v('ENGA. Y ENGAN.', 'vidrio', 6, h(17), a(26.7, 3), 1),
      v('ENGA. Y TRASL.', 'vidrio', 6, h(17), a(26.7, 3), 1),
    ],
    empaqueTipo: '7038',
    empaqueFactor: 1,
    empaqueExtraPorHoja: 0,
    accesorios: [
      { seccion: 'TORNILLERIA', descripcion: '10 X 1¨', cantidad: 16 },
      { seccion: 'TORNILLERIA', descripcion: '10 X 1¨', cantidad: 10 },
      { seccion: 'TORNILLERIA', descripcion: '8 X 1/2¨', cantidad: 6 },
      { seccion: 'CHAZOS', descripcion: '1/4¨', cantidad: 10 },
      { seccion: 'RODACHINAS', descripcion: '7038', cantidad: 4 },
      { seccion: 'GUIAS', descripcion: '7038 SUP', cantidad: 4 },
      { seccion: 'GUIAS', descripcion: '7038 INF', cantidad: 4 },
      { seccion: 'MANIJA', descripcion: 'ALUMINIO', cantidad: 1 },
      { seccion: 'SEGURO', descripcion: 'OVERSEA', cantidad: 1 },
    ],
  },

  {
    id: '7038-4-hojas',
    nombre: '7038 4 hojas',
    sistema: '7038',
    diseno: {
      tipo: 'corredera',
      apiladas: false,
      hojas: [
        { tipo: 'corredera', proporcion: 0.25 },
        { tipo: 'corredera', proporcion: 0.25 },
        { tipo: 'corredera', proporcion: 0.25 },
        { tipo: 'corredera', proporcion: 0.25 },
      ],
    },
    ejemplo: { ancho: 428.7, alto: 235.6 },
    piezas: [
      p('ALN-700', 'CABEZAL', a(), 1),
      p('ALN-775', 'SILLAR', a(), 1),
      p('ALN-702', 'JAMBA', h(1.2), 2),
      p('ALN-705', 'ENGANCHE 7038', h(3.5), 4),
      p('ALN-704', 'TRASLAPE 7038', h(3.5), 4),
      p('ALN-703', 'HORIZONTAL', a(-6.3, 4), 8),
      p('HSP-019', 'ADAPTADOR', h(3.5), 1),
    ],
    vidrios: [v('HOJAS', 'vidrio', 6, h(16.7), a(39.7, 4), 4)],
    empaqueTipo: '7038',
    empaqueFactor: 1,
    empaqueExtraPorHoja: 0,
    accesorios: [
      { seccion: 'TORNILLERIA', descripcion: '10 X 1¨', cantidad: 36 },
      { seccion: 'TORNILLERIA', descripcion: '10 X 1¨', cantidad: 10 },
      { seccion: 'TORNILLERIA', descripcion: '10 X 2¨', cantidad: 12 },
      { seccion: 'CHAZOS', descripcion: '1/4¨', cantidad: 12 },
      { seccion: 'RODACHINAS', descripcion: '7038', cantidad: 4 },
      { seccion: 'GUIAS', descripcion: '7038 SUP', cantidad: 4 },
      { seccion: 'GUIAS', descripcion: '7038 INF', cantidad: 4 },
      { seccion: 'MANIJA', descripcion: 'ALUMINIO', cantidad: 2 },
      { seccion: 'SEGURO', descripcion: 'OVERSEA', cantidad: 1 },
    ],
  },
];
