import { a, h, f, p, v } from './tipos.js';
import type { ModeloVentaneria } from './tipos.js';

/** Modelos de la familia 8025. */
export const modelos8025: ModeloVentaneria[] = [
  {
    id: '8025-2-hojas',
    nombre: '8025 2 hojas',
    sistema: '8025',
    diseno: {
      tipo: 'corredera',
      apiladas: false,
      hojas: [
        { tipo: 'corredera', proporcion: 0.5 },
        { tipo: 'corredera', proporcion: 0.5 },
      ],
    },
    ejemplo: { ancho: 176.6, alto: 121.5 },
    piezas: [
      p('ALN-392', 'CABEZAL', a(), 1),
      p('ALN-387', 'SILLAR', a(), 1),
      p('ALN-393', 'JAMBA', h(1), 2),
      p('ALN-391', 'ENGANCHE 8025', h(2.3), 2),
      p('ALN-388', 'TRASLAPE 8025', h(2.3), 2),
      p('ALN-389', 'HORIZONTAL SUP.', a(0.5, 2), 2),
      p('ALNA-390', 'HORIZONTAL INF.', a(0.5, 2), 2),
    ],
    vidrios: [v('HOJAS', 'vidrio', 5, h(10.2), { base: 'ancho', resta: 13.1, divisor: 2 }, 2)],
    empaqueTipo: '8025',
    empaqueFactor: 1,
    empaqueExtraPorHoja: 0,
    accesorios: [
      { seccion: 'TORNILLERIA', descripcion: '8 X 3/4¨ HOJAS', cantidad: 12 },
      { seccion: 'TORNILLERIA', descripcion: '8 X 1 1/2¨', cantidad: 10 },
      { seccion: 'TORNILLERIA', descripcion: '8 X 1/2¨', cantidad: 6 },
      { seccion: 'CHAZOS', descripcion: '1/4¨', cantidad: 10 },
      { seccion: 'RODACHINAS', descripcion: '8025 ACERO', cantidad: 2 },
      { seccion: 'GUIAS', descripcion: '8025 INFERIORES', cantidad: 2 },
      { seccion: 'GUIAS', descripcion: '8025 SUPERIORES', cantidad: 2 },
      { seccion: 'SEGURO', descripcion: 'JAGUAR DOBLE', cantidad: 1 },
    ],
  },

  {
    id: '8025-3-hojas',
    nombre: '8025 3 hojas',
    sistema: '8025',
    diseno: {
      tipo: 'corredera',
      apiladas: false,
      hojas: [
        { tipo: 'corredera', proporcion: 0.333 },
        { tipo: 'corredera', proporcion: 0.333 },
        { tipo: 'fija', proporcion: 0.334 },
      ],
    },
    ejemplo: { ancho: 291.4, alto: 250 },
    piezas: [
      p('ALN-392', 'CABEZAL', a(), 1),
      p('ALN-387', 'SILLAR', a(), 1),
      p('ALN-393', 'JAMBA', h(1.2), 2),
      p('ALN-391', 'ENGANCHE 8025 (FIJA)', h(2.7), 1),
      p('ALN-388', 'TRASLAPE 8025 (FIJA)', h(2.7), 1),
      p('ALN-389', 'HORIZONTAL SUP. (FIJA)', a(-2.3, 3), 1),
      p('ALNA-390', 'HORIZONTAL INF. (FIJA)', a(-2.3, 3), 1),
      p('ALN-391', 'ENGANCHE 8025 (CORR.)', h(2.7), 3),
      p('ALN-388', 'TRASLAPE 8025 (CORR.)', h(2.7), 1),
      p('ALN-389', 'HORIZONTAL SUP. (CORR.)', a(-2.3, 3), 2),
      p('ALNA-390', 'HORIZONTAL INF. (CORR.)', a(-2.3, 3), 2),
      p('ALN403', 'ADAPTADOR 8025', h(2.7), 1),
    ],
    vidrios: [v('HOJAS', 'vidrio', 6, h(11), a(14.8, 3), 3)],
    empaqueTipo: '8025',
    empaqueFactor: 1,
    empaqueExtraPorHoja: 0,
    accesorios: [
      { seccion: 'TORNILLERIA', descripcion: '8 X 3/4¨', cantidad: 16 },
      { seccion: 'TORNILLERIA', descripcion: '8 X 1 1/2¨', cantidad: 10 },
      { seccion: 'TORNILLERIA', descripcion: '8 X 1/2¨', cantidad: 6 },
      { seccion: 'CHAZOS', descripcion: '1/4¨', cantidad: 10 },
      { seccion: 'RODACHINAS', descripcion: '8025 ACERO', cantidad: 4 },
      { seccion: 'GUIAS', descripcion: '8025 INFERIORES', cantidad: 4 },
      { seccion: 'GUIAS', descripcion: '8025 SUPERIORES', cantidad: 4 },
      { seccion: 'SEGURO', descripcion: 'JAGUAR DOBLE', cantidad: 1 },
    ],
  },

  {
    id: '8025-4-hojas',
    nombre: '8025 4 hojas',
    sistema: '8025',
    diseno: {
      tipo: 'corredera',
      apiladas: false,
      hojas: [
        { tipo: 'corredera', proporcion: 0.25 },
        { tipo: 'corredera', proporcion: 0.25 },
        { tipo: 'corredera', proporcion: 0.25 },
        { tipo: 'corredera', proporcion: 0.25 },
      ],
    },
    ejemplo: { ancho: 300, alto: 200 },
    piezas: [
      p('ALN-392', 'CABEZAL', a(), 1),
      p('ALN-387', 'SILLAR', a(), 1),
      p('ALN-393', 'JAMBA', h(1), 2),
      p('ALN-391', 'ENGANCHE 8025', h(2), 4),
      p('ALN-388', 'TRASLAPE 8025', h(2), 4),
      p('ALN-403', 'ADAPTADOR 8025', h(2), 1),
      p('ALN-389', 'HORIZONTAL SUP.', a(-1.3, 4), 4),
      p('ALNA-390', 'HORIZONTAL INF.', a(-1.3, 4), 4),
    ],
    vidrios: [v('HOJAS', 'vidrio', 6, h(10.2), a(19.9, 4), 4)],
    empaqueTipo: '8025',
    empaqueFactor: 1,
    empaqueExtraPorHoja: 0,
    accesorios: [
      { seccion: 'TORNILLERIA', descripcion: '8 X 3/4¨', cantidad: 36 },
      { seccion: 'TORNILLERIA', descripcion: '8 X 1 1/2¨', cantidad: 10 },
      { seccion: 'TORNILLERIA', descripcion: '8 X 1/2¨', cantidad: 12 },
      { seccion: 'CHAZOS', descripcion: '1/4¨', cantidad: 10 },
      { seccion: 'RODACHINAS', descripcion: '8025 ACERO', cantidad: 4 },
      { seccion: 'GUIAS', descripcion: '8025 INF.', cantidad: 4 },
      { seccion: 'GUIAS', descripcion: '8025 SUP.', cantidad: 4 },
      { seccion: 'SEGURO', descripcion: 'JAGUAR DOBLE', cantidad: 1 },
    ],
  },
];
